name: melosys-skjema-web
services:
  express-server:
    build: .
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: "development"
      ENV: "dev"
      EXPRESS_PORT: "4000"
      EXPRESS_HOST: "::"
      API_URL: http://host.docker.internal:8090/api
      MOCK_DEKORATOREN: "true"
      USE_LOCAL_TOKEN: "true"
      MOCK_OAUTH_TOKEN_URL: http://host.docker.internal:8082/isso/token
      MOCK_OAUTH_CLIENT_ID: melosys-skjema-web
      MOCK_OAUTH_AUDIENCE: melosys-skjema-api
