apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: melosys-skjema-web
  namespace: teammelosys
  labels:
    team: teammelosys
spec:
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: /internal/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  idporten:
    enabled: true
    sidecar:
      autoLogin: true
      enabled: true
      level: idporten-loa-high
      locale: nb
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: melosys-skjema-api
  prometheus:
    enabled: true
    path: internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: NODE_ENV
      value: "production"
    - name: EXPRESS_HOST
      value: "::"
    - name: EXPRESS_PORT
      value: "8080"
    - name: ENV
      value: {{ENV}}
    - name: API_URL
      value: {{API_URL}}
    - name: API_SCOPE
      value: {{API_SCOPE}}
