name: melosys-skjema-web
services:
  express-server:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
      secrets:
        - npmrc
    ports:
      - "8081:8081"
    extra_hosts:
      - "localhost:${DC_HOST_IP:-0.0.0.0}"
    environment:
      NODE_ENV: "development"
      EXPRESS_PORT: "8081"
      EXPRESS_HOST: "::"
      USE_LOCAL_TOKEN: "true"
      LOCAL_TOKEN_ENDPOINT: http://host.docker.internal:8082/tokenx/token
      LOCAL_TOKEN_AUDIENCE: melosys-skjema-api
      API_URL: http://host.docker.internal:8090/api
      DEKORATOREN_API_URL: https://www.ekstern.dev.nav.no/person/nav-dekoratoren-api
      ENV: dev
  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    platform: linux/amd64
    ports:
      - "4000:4000"
    command: >
      --auto-login=true
      --openid.well-known-url=http://host.docker.internal:8082/isso/.well-known/openid-configuration
      --openid.client-secret=not-so-secret
      --openid.client-id=client-id
      --ingress=http://localhost:4000
      --bind-address=0.0.0.0:4000
      --upstream-host=localhost:8081
      --log-level=info
      --log-format=text
    restart: on-failure
    extra_hosts:
      # Wonderwall needs to both reach and redirect user agents to the mock-oauth2-server:
      # - 'mock-oauth2-server:8888' resolves from the container, but is not resolvable for user agents at the host (e.g. during redirects).
      # - 'localhost:8888' allows user agents to resolve redirects to the mock-oauth2-server, but breaks connectivity from the container itself.
      # This additional mapping allows the container to reach the mock-oauth2-server at 'localhost' through the host network, as well as allowing user agents to correctly resolve redirects.
      - localhost:host-gateway

secrets:
  npmrc:
    file: ~/.npmrc