version: '3.8'
name: melosys-skjema-web
services:
  express-server:
    build:
      context: .
      dockerfile: "Dockerfile"
      secrets:
        - npmrc
    ports:
      - "8081:8081"
    extra_hosts:
      - "localhost:${DC_HOST_IP:-0.0.0.0}"
    environment:
      NODE_ENV: "development"
      EXPRESS_PORT: "8081"
      EXPRESS_HOST: "::"
      API_SCOPE: dummy-api-scope
      API_URL: http://localhost:8080
      ENV: dev
      NESTED_PATH: /melosys-skjema

secrets:
  npmrc:
    file: ~/.npmrc