/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkjemaRouteImport } from './routes/skjema'
import { Route as RollevelgerRouteImport } from './routes/rollevelger'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkjemaIndexRouteImport } from './routes/skjema.index'
import { Route as SkjemaArbeidstakerRouteImport } from './routes/skjema.arbeidstaker'
import { Route as SkjemaArbeidsgiverRouteImport } from './routes/skjema.arbeidsgiver'
import { Route as SkjemaArbeidstakerIndexRouteImport } from './routes/skjema.arbeidstaker.index'
import { Route as SkjemaArbeidsgiverIndexRouteImport } from './routes/skjema.arbeidsgiver.index'
import { Route as SkjemaArbeidstakerIdTilleggsopplysningerRouteImport } from './routes/skjema.arbeidstaker.$id.tilleggsopplysninger'
import { Route as SkjemaArbeidstakerIdSkatteforholdOgInntektRouteImport } from './routes/skjema.arbeidstaker.$id.skatteforhold-og-inntekt'
import { Route as SkjemaArbeidstakerIdOppsummeringRouteImport } from './routes/skjema.arbeidstaker.$id.oppsummering'
import { Route as SkjemaArbeidstakerIdFamiliemedlemmerRouteImport } from './routes/skjema.arbeidstaker.$id.familiemedlemmer'
import { Route as SkjemaArbeidstakerIdArbeidstakerenRouteImport } from './routes/skjema.arbeidstaker.$id.arbeidstakeren'
import { Route as SkjemaArbeidsgiverIdUtenlandsoppdragetRouteImport } from './routes/skjema.arbeidsgiver.$id.utenlandsoppdraget'
import { Route as SkjemaArbeidsgiverIdOppsummeringRouteImport } from './routes/skjema.arbeidsgiver.$id.oppsummering'
import { Route as SkjemaArbeidsgiverIdArbeidstakerensLonnRouteImport } from './routes/skjema.arbeidsgiver.$id.arbeidstakerens-lonn'
import { Route as SkjemaArbeidsgiverIdArbeidstakerenRouteImport } from './routes/skjema.arbeidsgiver.$id.arbeidstakeren'
import { Route as SkjemaArbeidsgiverIdArbeidsstedIUtlandetRouteImport } from './routes/skjema.arbeidsgiver.$id.arbeidssted-i-utlandet'
import { Route as SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRouteImport } from './routes/skjema.arbeidsgiver.$id.arbeidsgiverens-virksomhet-i-norge'
import { Route as SkjemaArbeidsgiverIdArbeidsgiverenRouteImport } from './routes/skjema.arbeidsgiver.$id.arbeidsgiveren'

const SkjemaRoute = SkjemaRouteImport.update({
  id: '/skjema',
  path: '/skjema',
  getParentRoute: () => rootRouteImport,
} as any)
const RollevelgerRoute = RollevelgerRouteImport.update({
  id: '/rollevelger',
  path: '/rollevelger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkjemaIndexRoute = SkjemaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkjemaRoute,
} as any)
const SkjemaArbeidstakerRoute = SkjemaArbeidstakerRouteImport.update({
  id: '/arbeidstaker',
  path: '/arbeidstaker',
  getParentRoute: () => SkjemaRoute,
} as any)
const SkjemaArbeidsgiverRoute = SkjemaArbeidsgiverRouteImport.update({
  id: '/arbeidsgiver',
  path: '/arbeidsgiver',
  getParentRoute: () => SkjemaRoute,
} as any)
const SkjemaArbeidstakerIndexRoute = SkjemaArbeidstakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkjemaArbeidstakerRoute,
} as any)
const SkjemaArbeidsgiverIndexRoute = SkjemaArbeidsgiverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkjemaArbeidsgiverRoute,
} as any)
const SkjemaArbeidstakerIdTilleggsopplysningerRoute =
  SkjemaArbeidstakerIdTilleggsopplysningerRouteImport.update({
    id: '/$id/tilleggsopplysninger',
    path: '/$id/tilleggsopplysninger',
    getParentRoute: () => SkjemaArbeidstakerRoute,
  } as any)
const SkjemaArbeidstakerIdSkatteforholdOgInntektRoute =
  SkjemaArbeidstakerIdSkatteforholdOgInntektRouteImport.update({
    id: '/$id/skatteforhold-og-inntekt',
    path: '/$id/skatteforhold-og-inntekt',
    getParentRoute: () => SkjemaArbeidstakerRoute,
  } as any)
const SkjemaArbeidstakerIdOppsummeringRoute =
  SkjemaArbeidstakerIdOppsummeringRouteImport.update({
    id: '/$id/oppsummering',
    path: '/$id/oppsummering',
    getParentRoute: () => SkjemaArbeidstakerRoute,
  } as any)
const SkjemaArbeidstakerIdFamiliemedlemmerRoute =
  SkjemaArbeidstakerIdFamiliemedlemmerRouteImport.update({
    id: '/$id/familiemedlemmer',
    path: '/$id/familiemedlemmer',
    getParentRoute: () => SkjemaArbeidstakerRoute,
  } as any)
const SkjemaArbeidstakerIdArbeidstakerenRoute =
  SkjemaArbeidstakerIdArbeidstakerenRouteImport.update({
    id: '/$id/arbeidstakeren',
    path: '/$id/arbeidstakeren',
    getParentRoute: () => SkjemaArbeidstakerRoute,
  } as any)
const SkjemaArbeidsgiverIdUtenlandsoppdragetRoute =
  SkjemaArbeidsgiverIdUtenlandsoppdragetRouteImport.update({
    id: '/$id/utenlandsoppdraget',
    path: '/$id/utenlandsoppdraget',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)
const SkjemaArbeidsgiverIdOppsummeringRoute =
  SkjemaArbeidsgiverIdOppsummeringRouteImport.update({
    id: '/$id/oppsummering',
    path: '/$id/oppsummering',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)
const SkjemaArbeidsgiverIdArbeidstakerensLonnRoute =
  SkjemaArbeidsgiverIdArbeidstakerensLonnRouteImport.update({
    id: '/$id/arbeidstakerens-lonn',
    path: '/$id/arbeidstakerens-lonn',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)
const SkjemaArbeidsgiverIdArbeidstakerenRoute =
  SkjemaArbeidsgiverIdArbeidstakerenRouteImport.update({
    id: '/$id/arbeidstakeren',
    path: '/$id/arbeidstakeren',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)
const SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute =
  SkjemaArbeidsgiverIdArbeidsstedIUtlandetRouteImport.update({
    id: '/$id/arbeidssted-i-utlandet',
    path: '/$id/arbeidssted-i-utlandet',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)
const SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute =
  SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRouteImport.update({
    id: '/$id/arbeidsgiverens-virksomhet-i-norge',
    path: '/$id/arbeidsgiverens-virksomhet-i-norge',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)
const SkjemaArbeidsgiverIdArbeidsgiverenRoute =
  SkjemaArbeidsgiverIdArbeidsgiverenRouteImport.update({
    id: '/$id/arbeidsgiveren',
    path: '/$id/arbeidsgiveren',
    getParentRoute: () => SkjemaArbeidsgiverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rollevelger': typeof RollevelgerRoute
  '/skjema': typeof SkjemaRouteWithChildren
  '/skjema/arbeidsgiver': typeof SkjemaArbeidsgiverRouteWithChildren
  '/skjema/arbeidstaker': typeof SkjemaArbeidstakerRouteWithChildren
  '/skjema/': typeof SkjemaIndexRoute
  '/skjema/arbeidsgiver/': typeof SkjemaArbeidsgiverIndexRoute
  '/skjema/arbeidstaker/': typeof SkjemaArbeidstakerIndexRoute
  '/skjema/arbeidsgiver/$id/arbeidsgiveren': typeof SkjemaArbeidsgiverIdArbeidsgiverenRoute
  '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge': typeof SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute
  '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet': typeof SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute
  '/skjema/arbeidsgiver/$id/arbeidstakeren': typeof SkjemaArbeidsgiverIdArbeidstakerenRoute
  '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn': typeof SkjemaArbeidsgiverIdArbeidstakerensLonnRoute
  '/skjema/arbeidsgiver/$id/oppsummering': typeof SkjemaArbeidsgiverIdOppsummeringRoute
  '/skjema/arbeidsgiver/$id/utenlandsoppdraget': typeof SkjemaArbeidsgiverIdUtenlandsoppdragetRoute
  '/skjema/arbeidstaker/$id/arbeidstakeren': typeof SkjemaArbeidstakerIdArbeidstakerenRoute
  '/skjema/arbeidstaker/$id/familiemedlemmer': typeof SkjemaArbeidstakerIdFamiliemedlemmerRoute
  '/skjema/arbeidstaker/$id/oppsummering': typeof SkjemaArbeidstakerIdOppsummeringRoute
  '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt': typeof SkjemaArbeidstakerIdSkatteforholdOgInntektRoute
  '/skjema/arbeidstaker/$id/tilleggsopplysninger': typeof SkjemaArbeidstakerIdTilleggsopplysningerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rollevelger': typeof RollevelgerRoute
  '/skjema': typeof SkjemaIndexRoute
  '/skjema/arbeidsgiver': typeof SkjemaArbeidsgiverIndexRoute
  '/skjema/arbeidstaker': typeof SkjemaArbeidstakerIndexRoute
  '/skjema/arbeidsgiver/$id/arbeidsgiveren': typeof SkjemaArbeidsgiverIdArbeidsgiverenRoute
  '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge': typeof SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute
  '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet': typeof SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute
  '/skjema/arbeidsgiver/$id/arbeidstakeren': typeof SkjemaArbeidsgiverIdArbeidstakerenRoute
  '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn': typeof SkjemaArbeidsgiverIdArbeidstakerensLonnRoute
  '/skjema/arbeidsgiver/$id/oppsummering': typeof SkjemaArbeidsgiverIdOppsummeringRoute
  '/skjema/arbeidsgiver/$id/utenlandsoppdraget': typeof SkjemaArbeidsgiverIdUtenlandsoppdragetRoute
  '/skjema/arbeidstaker/$id/arbeidstakeren': typeof SkjemaArbeidstakerIdArbeidstakerenRoute
  '/skjema/arbeidstaker/$id/familiemedlemmer': typeof SkjemaArbeidstakerIdFamiliemedlemmerRoute
  '/skjema/arbeidstaker/$id/oppsummering': typeof SkjemaArbeidstakerIdOppsummeringRoute
  '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt': typeof SkjemaArbeidstakerIdSkatteforholdOgInntektRoute
  '/skjema/arbeidstaker/$id/tilleggsopplysninger': typeof SkjemaArbeidstakerIdTilleggsopplysningerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rollevelger': typeof RollevelgerRoute
  '/skjema': typeof SkjemaRouteWithChildren
  '/skjema/arbeidsgiver': typeof SkjemaArbeidsgiverRouteWithChildren
  '/skjema/arbeidstaker': typeof SkjemaArbeidstakerRouteWithChildren
  '/skjema/': typeof SkjemaIndexRoute
  '/skjema/arbeidsgiver/': typeof SkjemaArbeidsgiverIndexRoute
  '/skjema/arbeidstaker/': typeof SkjemaArbeidstakerIndexRoute
  '/skjema/arbeidsgiver/$id/arbeidsgiveren': typeof SkjemaArbeidsgiverIdArbeidsgiverenRoute
  '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge': typeof SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute
  '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet': typeof SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute
  '/skjema/arbeidsgiver/$id/arbeidstakeren': typeof SkjemaArbeidsgiverIdArbeidstakerenRoute
  '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn': typeof SkjemaArbeidsgiverIdArbeidstakerensLonnRoute
  '/skjema/arbeidsgiver/$id/oppsummering': typeof SkjemaArbeidsgiverIdOppsummeringRoute
  '/skjema/arbeidsgiver/$id/utenlandsoppdraget': typeof SkjemaArbeidsgiverIdUtenlandsoppdragetRoute
  '/skjema/arbeidstaker/$id/arbeidstakeren': typeof SkjemaArbeidstakerIdArbeidstakerenRoute
  '/skjema/arbeidstaker/$id/familiemedlemmer': typeof SkjemaArbeidstakerIdFamiliemedlemmerRoute
  '/skjema/arbeidstaker/$id/oppsummering': typeof SkjemaArbeidstakerIdOppsummeringRoute
  '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt': typeof SkjemaArbeidstakerIdSkatteforholdOgInntektRoute
  '/skjema/arbeidstaker/$id/tilleggsopplysninger': typeof SkjemaArbeidstakerIdTilleggsopplysningerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rollevelger'
    | '/skjema'
    | '/skjema/arbeidsgiver'
    | '/skjema/arbeidstaker'
    | '/skjema/'
    | '/skjema/arbeidsgiver/'
    | '/skjema/arbeidstaker/'
    | '/skjema/arbeidsgiver/$id/arbeidsgiveren'
    | '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge'
    | '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet'
    | '/skjema/arbeidsgiver/$id/arbeidstakeren'
    | '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn'
    | '/skjema/arbeidsgiver/$id/oppsummering'
    | '/skjema/arbeidsgiver/$id/utenlandsoppdraget'
    | '/skjema/arbeidstaker/$id/arbeidstakeren'
    | '/skjema/arbeidstaker/$id/familiemedlemmer'
    | '/skjema/arbeidstaker/$id/oppsummering'
    | '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt'
    | '/skjema/arbeidstaker/$id/tilleggsopplysninger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rollevelger'
    | '/skjema'
    | '/skjema/arbeidsgiver'
    | '/skjema/arbeidstaker'
    | '/skjema/arbeidsgiver/$id/arbeidsgiveren'
    | '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge'
    | '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet'
    | '/skjema/arbeidsgiver/$id/arbeidstakeren'
    | '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn'
    | '/skjema/arbeidsgiver/$id/oppsummering'
    | '/skjema/arbeidsgiver/$id/utenlandsoppdraget'
    | '/skjema/arbeidstaker/$id/arbeidstakeren'
    | '/skjema/arbeidstaker/$id/familiemedlemmer'
    | '/skjema/arbeidstaker/$id/oppsummering'
    | '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt'
    | '/skjema/arbeidstaker/$id/tilleggsopplysninger'
  id:
    | '__root__'
    | '/'
    | '/rollevelger'
    | '/skjema'
    | '/skjema/arbeidsgiver'
    | '/skjema/arbeidstaker'
    | '/skjema/'
    | '/skjema/arbeidsgiver/'
    | '/skjema/arbeidstaker/'
    | '/skjema/arbeidsgiver/$id/arbeidsgiveren'
    | '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge'
    | '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet'
    | '/skjema/arbeidsgiver/$id/arbeidstakeren'
    | '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn'
    | '/skjema/arbeidsgiver/$id/oppsummering'
    | '/skjema/arbeidsgiver/$id/utenlandsoppdraget'
    | '/skjema/arbeidstaker/$id/arbeidstakeren'
    | '/skjema/arbeidstaker/$id/familiemedlemmer'
    | '/skjema/arbeidstaker/$id/oppsummering'
    | '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt'
    | '/skjema/arbeidstaker/$id/tilleggsopplysninger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RollevelgerRoute: typeof RollevelgerRoute
  SkjemaRoute: typeof SkjemaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skjema': {
      id: '/skjema'
      path: '/skjema'
      fullPath: '/skjema'
      preLoaderRoute: typeof SkjemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rollevelger': {
      id: '/rollevelger'
      path: '/rollevelger'
      fullPath: '/rollevelger'
      preLoaderRoute: typeof RollevelgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skjema/': {
      id: '/skjema/'
      path: '/'
      fullPath: '/skjema/'
      preLoaderRoute: typeof SkjemaIndexRouteImport
      parentRoute: typeof SkjemaRoute
    }
    '/skjema/arbeidstaker': {
      id: '/skjema/arbeidstaker'
      path: '/arbeidstaker'
      fullPath: '/skjema/arbeidstaker'
      preLoaderRoute: typeof SkjemaArbeidstakerRouteImport
      parentRoute: typeof SkjemaRoute
    }
    '/skjema/arbeidsgiver': {
      id: '/skjema/arbeidsgiver'
      path: '/arbeidsgiver'
      fullPath: '/skjema/arbeidsgiver'
      preLoaderRoute: typeof SkjemaArbeidsgiverRouteImport
      parentRoute: typeof SkjemaRoute
    }
    '/skjema/arbeidstaker/': {
      id: '/skjema/arbeidstaker/'
      path: '/'
      fullPath: '/skjema/arbeidstaker/'
      preLoaderRoute: typeof SkjemaArbeidstakerIndexRouteImport
      parentRoute: typeof SkjemaArbeidstakerRoute
    }
    '/skjema/arbeidsgiver/': {
      id: '/skjema/arbeidsgiver/'
      path: '/'
      fullPath: '/skjema/arbeidsgiver/'
      preLoaderRoute: typeof SkjemaArbeidsgiverIndexRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidstaker/$id/tilleggsopplysninger': {
      id: '/skjema/arbeidstaker/$id/tilleggsopplysninger'
      path: '/$id/tilleggsopplysninger'
      fullPath: '/skjema/arbeidstaker/$id/tilleggsopplysninger'
      preLoaderRoute: typeof SkjemaArbeidstakerIdTilleggsopplysningerRouteImport
      parentRoute: typeof SkjemaArbeidstakerRoute
    }
    '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt': {
      id: '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt'
      path: '/$id/skatteforhold-og-inntekt'
      fullPath: '/skjema/arbeidstaker/$id/skatteforhold-og-inntekt'
      preLoaderRoute: typeof SkjemaArbeidstakerIdSkatteforholdOgInntektRouteImport
      parentRoute: typeof SkjemaArbeidstakerRoute
    }
    '/skjema/arbeidstaker/$id/oppsummering': {
      id: '/skjema/arbeidstaker/$id/oppsummering'
      path: '/$id/oppsummering'
      fullPath: '/skjema/arbeidstaker/$id/oppsummering'
      preLoaderRoute: typeof SkjemaArbeidstakerIdOppsummeringRouteImport
      parentRoute: typeof SkjemaArbeidstakerRoute
    }
    '/skjema/arbeidstaker/$id/familiemedlemmer': {
      id: '/skjema/arbeidstaker/$id/familiemedlemmer'
      path: '/$id/familiemedlemmer'
      fullPath: '/skjema/arbeidstaker/$id/familiemedlemmer'
      preLoaderRoute: typeof SkjemaArbeidstakerIdFamiliemedlemmerRouteImport
      parentRoute: typeof SkjemaArbeidstakerRoute
    }
    '/skjema/arbeidstaker/$id/arbeidstakeren': {
      id: '/skjema/arbeidstaker/$id/arbeidstakeren'
      path: '/$id/arbeidstakeren'
      fullPath: '/skjema/arbeidstaker/$id/arbeidstakeren'
      preLoaderRoute: typeof SkjemaArbeidstakerIdArbeidstakerenRouteImport
      parentRoute: typeof SkjemaArbeidstakerRoute
    }
    '/skjema/arbeidsgiver/$id/utenlandsoppdraget': {
      id: '/skjema/arbeidsgiver/$id/utenlandsoppdraget'
      path: '/$id/utenlandsoppdraget'
      fullPath: '/skjema/arbeidsgiver/$id/utenlandsoppdraget'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdUtenlandsoppdragetRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidsgiver/$id/oppsummering': {
      id: '/skjema/arbeidsgiver/$id/oppsummering'
      path: '/$id/oppsummering'
      fullPath: '/skjema/arbeidsgiver/$id/oppsummering'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdOppsummeringRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn': {
      id: '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn'
      path: '/$id/arbeidstakerens-lonn'
      fullPath: '/skjema/arbeidsgiver/$id/arbeidstakerens-lonn'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdArbeidstakerensLonnRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidsgiver/$id/arbeidstakeren': {
      id: '/skjema/arbeidsgiver/$id/arbeidstakeren'
      path: '/$id/arbeidstakeren'
      fullPath: '/skjema/arbeidsgiver/$id/arbeidstakeren'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdArbeidstakerenRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet': {
      id: '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet'
      path: '/$id/arbeidssted-i-utlandet'
      fullPath: '/skjema/arbeidsgiver/$id/arbeidssted-i-utlandet'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdArbeidsstedIUtlandetRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge': {
      id: '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge'
      path: '/$id/arbeidsgiverens-virksomhet-i-norge'
      fullPath: '/skjema/arbeidsgiver/$id/arbeidsgiverens-virksomhet-i-norge'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
    '/skjema/arbeidsgiver/$id/arbeidsgiveren': {
      id: '/skjema/arbeidsgiver/$id/arbeidsgiveren'
      path: '/$id/arbeidsgiveren'
      fullPath: '/skjema/arbeidsgiver/$id/arbeidsgiveren'
      preLoaderRoute: typeof SkjemaArbeidsgiverIdArbeidsgiverenRouteImport
      parentRoute: typeof SkjemaArbeidsgiverRoute
    }
  }
}

interface SkjemaArbeidsgiverRouteChildren {
  SkjemaArbeidsgiverIndexRoute: typeof SkjemaArbeidsgiverIndexRoute
  SkjemaArbeidsgiverIdArbeidsgiverenRoute: typeof SkjemaArbeidsgiverIdArbeidsgiverenRoute
  SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute: typeof SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute
  SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute: typeof SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute
  SkjemaArbeidsgiverIdArbeidstakerenRoute: typeof SkjemaArbeidsgiverIdArbeidstakerenRoute
  SkjemaArbeidsgiverIdArbeidstakerensLonnRoute: typeof SkjemaArbeidsgiverIdArbeidstakerensLonnRoute
  SkjemaArbeidsgiverIdOppsummeringRoute: typeof SkjemaArbeidsgiverIdOppsummeringRoute
  SkjemaArbeidsgiverIdUtenlandsoppdragetRoute: typeof SkjemaArbeidsgiverIdUtenlandsoppdragetRoute
}

const SkjemaArbeidsgiverRouteChildren: SkjemaArbeidsgiverRouteChildren = {
  SkjemaArbeidsgiverIndexRoute: SkjemaArbeidsgiverIndexRoute,
  SkjemaArbeidsgiverIdArbeidsgiverenRoute:
    SkjemaArbeidsgiverIdArbeidsgiverenRoute,
  SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute:
    SkjemaArbeidsgiverIdArbeidsgiverensVirksomhetINorgeRoute,
  SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute:
    SkjemaArbeidsgiverIdArbeidsstedIUtlandetRoute,
  SkjemaArbeidsgiverIdArbeidstakerenRoute:
    SkjemaArbeidsgiverIdArbeidstakerenRoute,
  SkjemaArbeidsgiverIdArbeidstakerensLonnRoute:
    SkjemaArbeidsgiverIdArbeidstakerensLonnRoute,
  SkjemaArbeidsgiverIdOppsummeringRoute: SkjemaArbeidsgiverIdOppsummeringRoute,
  SkjemaArbeidsgiverIdUtenlandsoppdragetRoute:
    SkjemaArbeidsgiverIdUtenlandsoppdragetRoute,
}

const SkjemaArbeidsgiverRouteWithChildren =
  SkjemaArbeidsgiverRoute._addFileChildren(SkjemaArbeidsgiverRouteChildren)

interface SkjemaArbeidstakerRouteChildren {
  SkjemaArbeidstakerIndexRoute: typeof SkjemaArbeidstakerIndexRoute
  SkjemaArbeidstakerIdArbeidstakerenRoute: typeof SkjemaArbeidstakerIdArbeidstakerenRoute
  SkjemaArbeidstakerIdFamiliemedlemmerRoute: typeof SkjemaArbeidstakerIdFamiliemedlemmerRoute
  SkjemaArbeidstakerIdOppsummeringRoute: typeof SkjemaArbeidstakerIdOppsummeringRoute
  SkjemaArbeidstakerIdSkatteforholdOgInntektRoute: typeof SkjemaArbeidstakerIdSkatteforholdOgInntektRoute
  SkjemaArbeidstakerIdTilleggsopplysningerRoute: typeof SkjemaArbeidstakerIdTilleggsopplysningerRoute
}

const SkjemaArbeidstakerRouteChildren: SkjemaArbeidstakerRouteChildren = {
  SkjemaArbeidstakerIndexRoute: SkjemaArbeidstakerIndexRoute,
  SkjemaArbeidstakerIdArbeidstakerenRoute:
    SkjemaArbeidstakerIdArbeidstakerenRoute,
  SkjemaArbeidstakerIdFamiliemedlemmerRoute:
    SkjemaArbeidstakerIdFamiliemedlemmerRoute,
  SkjemaArbeidstakerIdOppsummeringRoute: SkjemaArbeidstakerIdOppsummeringRoute,
  SkjemaArbeidstakerIdSkatteforholdOgInntektRoute:
    SkjemaArbeidstakerIdSkatteforholdOgInntektRoute,
  SkjemaArbeidstakerIdTilleggsopplysningerRoute:
    SkjemaArbeidstakerIdTilleggsopplysningerRoute,
}

const SkjemaArbeidstakerRouteWithChildren =
  SkjemaArbeidstakerRoute._addFileChildren(SkjemaArbeidstakerRouteChildren)

interface SkjemaRouteChildren {
  SkjemaArbeidsgiverRoute: typeof SkjemaArbeidsgiverRouteWithChildren
  SkjemaArbeidstakerRoute: typeof SkjemaArbeidstakerRouteWithChildren
  SkjemaIndexRoute: typeof SkjemaIndexRoute
}

const SkjemaRouteChildren: SkjemaRouteChildren = {
  SkjemaArbeidsgiverRoute: SkjemaArbeidsgiverRouteWithChildren,
  SkjemaArbeidstakerRoute: SkjemaArbeidstakerRouteWithChildren,
  SkjemaIndexRoute: SkjemaIndexRoute,
}

const SkjemaRouteWithChildren =
  SkjemaRoute._addFileChildren(SkjemaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RollevelgerRoute: RollevelgerRoute,
  SkjemaRoute: SkjemaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
