/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkjemaRouteImport } from './routes/skjema'
import { Route as RepresentasjonRouteImport } from './routes/representasjon'
import { Route as OversiktRouteImport } from './routes/oversikt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkjemaIndexRouteImport } from './routes/skjema.index'
import { Route as RepresentasjonIndexRouteImport } from './routes/representasjon.index'
import { Route as OversiktIndexRouteImport } from './routes/oversikt.index'
import { Route as SkjemaIdRouteImport } from './routes/skjema.$id'
import { Route as RepresentasjonVelgRadgiverfirmaRouteImport } from './routes/representasjon.velg-radgiverfirma'
import { Route as SkjemaIdIndexRouteImport } from './routes/skjema.$id.index'
import { Route as SkjemaIdVedleggRouteImport } from './routes/skjema.$id.vedlegg'
import { Route as SkjemaIdUtsendingsperiodeOgLandRouteImport } from './routes/skjema.$id.utsendingsperiode-og-land'
import { Route as SkjemaIdUtenlandsoppdragetRouteImport } from './routes/skjema.$id.utenlandsoppdraget'
import { Route as SkjemaIdTilleggsopplysningerRouteImport } from './routes/skjema.$id.tilleggsopplysninger'
import { Route as SkjemaIdSkatteforholdOgInntektRouteImport } from './routes/skjema.$id.skatteforhold-og-inntekt'
import { Route as SkjemaIdOppsummeringRouteImport } from './routes/skjema.$id.oppsummering'
import { Route as SkjemaIdKvitteringRouteImport } from './routes/skjema.$id.kvittering'
import { Route as SkjemaIdInnsendtRouteImport } from './routes/skjema.$id.innsendt'
import { Route as SkjemaIdFamiliemedlemmerRouteImport } from './routes/skjema.$id.familiemedlemmer'
import { Route as SkjemaIdArbeidstakerensLonnRouteImport } from './routes/skjema.$id.arbeidstakerens-lonn'
import { Route as SkjemaIdArbeidsstedIUtlandetRouteImport } from './routes/skjema.$id.arbeidssted-i-utlandet'
import { Route as SkjemaIdArbeidssituasjonRouteImport } from './routes/skjema.$id.arbeidssituasjon'
import { Route as SkjemaIdArbeidsgiverensVirksomhetINorgeRouteImport } from './routes/skjema.$id.arbeidsgiverens-virksomhet-i-norge'

const SkjemaRoute = SkjemaRouteImport.update({
  id: '/skjema',
  path: '/skjema',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentasjonRoute = RepresentasjonRouteImport.update({
  id: '/representasjon',
  path: '/representasjon',
  getParentRoute: () => rootRouteImport,
} as any)
const OversiktRoute = OversiktRouteImport.update({
  id: '/oversikt',
  path: '/oversikt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkjemaIndexRoute = SkjemaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkjemaRoute,
} as any)
const RepresentasjonIndexRoute = RepresentasjonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepresentasjonRoute,
} as any)
const OversiktIndexRoute = OversiktIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OversiktRoute,
} as any)
const SkjemaIdRoute = SkjemaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SkjemaRoute,
} as any)
const RepresentasjonVelgRadgiverfirmaRoute =
  RepresentasjonVelgRadgiverfirmaRouteImport.update({
    id: '/velg-radgiverfirma',
    path: '/velg-radgiverfirma',
    getParentRoute: () => RepresentasjonRoute,
  } as any)
const SkjemaIdIndexRoute = SkjemaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkjemaIdRoute,
} as any)
const SkjemaIdVedleggRoute = SkjemaIdVedleggRouteImport.update({
  id: '/vedlegg',
  path: '/vedlegg',
  getParentRoute: () => SkjemaIdRoute,
} as any)
const SkjemaIdUtsendingsperiodeOgLandRoute =
  SkjemaIdUtsendingsperiodeOgLandRouteImport.update({
    id: '/utsendingsperiode-og-land',
    path: '/utsendingsperiode-og-land',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdUtenlandsoppdragetRoute =
  SkjemaIdUtenlandsoppdragetRouteImport.update({
    id: '/utenlandsoppdraget',
    path: '/utenlandsoppdraget',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdTilleggsopplysningerRoute =
  SkjemaIdTilleggsopplysningerRouteImport.update({
    id: '/tilleggsopplysninger',
    path: '/tilleggsopplysninger',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdSkatteforholdOgInntektRoute =
  SkjemaIdSkatteforholdOgInntektRouteImport.update({
    id: '/skatteforhold-og-inntekt',
    path: '/skatteforhold-og-inntekt',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdOppsummeringRoute = SkjemaIdOppsummeringRouteImport.update({
  id: '/oppsummering',
  path: '/oppsummering',
  getParentRoute: () => SkjemaIdRoute,
} as any)
const SkjemaIdKvitteringRoute = SkjemaIdKvitteringRouteImport.update({
  id: '/kvittering',
  path: '/kvittering',
  getParentRoute: () => SkjemaIdRoute,
} as any)
const SkjemaIdInnsendtRoute = SkjemaIdInnsendtRouteImport.update({
  id: '/innsendt',
  path: '/innsendt',
  getParentRoute: () => SkjemaIdRoute,
} as any)
const SkjemaIdFamiliemedlemmerRoute =
  SkjemaIdFamiliemedlemmerRouteImport.update({
    id: '/familiemedlemmer',
    path: '/familiemedlemmer',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdArbeidstakerensLonnRoute =
  SkjemaIdArbeidstakerensLonnRouteImport.update({
    id: '/arbeidstakerens-lonn',
    path: '/arbeidstakerens-lonn',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdArbeidsstedIUtlandetRoute =
  SkjemaIdArbeidsstedIUtlandetRouteImport.update({
    id: '/arbeidssted-i-utlandet',
    path: '/arbeidssted-i-utlandet',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdArbeidssituasjonRoute =
  SkjemaIdArbeidssituasjonRouteImport.update({
    id: '/arbeidssituasjon',
    path: '/arbeidssituasjon',
    getParentRoute: () => SkjemaIdRoute,
  } as any)
const SkjemaIdArbeidsgiverensVirksomhetINorgeRoute =
  SkjemaIdArbeidsgiverensVirksomhetINorgeRouteImport.update({
    id: '/arbeidsgiverens-virksomhet-i-norge',
    path: '/arbeidsgiverens-virksomhet-i-norge',
    getParentRoute: () => SkjemaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oversikt': typeof OversiktRouteWithChildren
  '/representasjon': typeof RepresentasjonRouteWithChildren
  '/skjema': typeof SkjemaRouteWithChildren
  '/representasjon/velg-radgiverfirma': typeof RepresentasjonVelgRadgiverfirmaRoute
  '/skjema/$id': typeof SkjemaIdRouteWithChildren
  '/oversikt/': typeof OversiktIndexRoute
  '/representasjon/': typeof RepresentasjonIndexRoute
  '/skjema/': typeof SkjemaIndexRoute
  '/skjema/$id/arbeidsgiverens-virksomhet-i-norge': typeof SkjemaIdArbeidsgiverensVirksomhetINorgeRoute
  '/skjema/$id/arbeidssituasjon': typeof SkjemaIdArbeidssituasjonRoute
  '/skjema/$id/arbeidssted-i-utlandet': typeof SkjemaIdArbeidsstedIUtlandetRoute
  '/skjema/$id/arbeidstakerens-lonn': typeof SkjemaIdArbeidstakerensLonnRoute
  '/skjema/$id/familiemedlemmer': typeof SkjemaIdFamiliemedlemmerRoute
  '/skjema/$id/innsendt': typeof SkjemaIdInnsendtRoute
  '/skjema/$id/kvittering': typeof SkjemaIdKvitteringRoute
  '/skjema/$id/oppsummering': typeof SkjemaIdOppsummeringRoute
  '/skjema/$id/skatteforhold-og-inntekt': typeof SkjemaIdSkatteforholdOgInntektRoute
  '/skjema/$id/tilleggsopplysninger': typeof SkjemaIdTilleggsopplysningerRoute
  '/skjema/$id/utenlandsoppdraget': typeof SkjemaIdUtenlandsoppdragetRoute
  '/skjema/$id/utsendingsperiode-og-land': typeof SkjemaIdUtsendingsperiodeOgLandRoute
  '/skjema/$id/vedlegg': typeof SkjemaIdVedleggRoute
  '/skjema/$id/': typeof SkjemaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/representasjon/velg-radgiverfirma': typeof RepresentasjonVelgRadgiverfirmaRoute
  '/oversikt': typeof OversiktIndexRoute
  '/representasjon': typeof RepresentasjonIndexRoute
  '/skjema': typeof SkjemaIndexRoute
  '/skjema/$id/arbeidsgiverens-virksomhet-i-norge': typeof SkjemaIdArbeidsgiverensVirksomhetINorgeRoute
  '/skjema/$id/arbeidssituasjon': typeof SkjemaIdArbeidssituasjonRoute
  '/skjema/$id/arbeidssted-i-utlandet': typeof SkjemaIdArbeidsstedIUtlandetRoute
  '/skjema/$id/arbeidstakerens-lonn': typeof SkjemaIdArbeidstakerensLonnRoute
  '/skjema/$id/familiemedlemmer': typeof SkjemaIdFamiliemedlemmerRoute
  '/skjema/$id/innsendt': typeof SkjemaIdInnsendtRoute
  '/skjema/$id/kvittering': typeof SkjemaIdKvitteringRoute
  '/skjema/$id/oppsummering': typeof SkjemaIdOppsummeringRoute
  '/skjema/$id/skatteforhold-og-inntekt': typeof SkjemaIdSkatteforholdOgInntektRoute
  '/skjema/$id/tilleggsopplysninger': typeof SkjemaIdTilleggsopplysningerRoute
  '/skjema/$id/utenlandsoppdraget': typeof SkjemaIdUtenlandsoppdragetRoute
  '/skjema/$id/utsendingsperiode-og-land': typeof SkjemaIdUtsendingsperiodeOgLandRoute
  '/skjema/$id/vedlegg': typeof SkjemaIdVedleggRoute
  '/skjema/$id': typeof SkjemaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oversikt': typeof OversiktRouteWithChildren
  '/representasjon': typeof RepresentasjonRouteWithChildren
  '/skjema': typeof SkjemaRouteWithChildren
  '/representasjon/velg-radgiverfirma': typeof RepresentasjonVelgRadgiverfirmaRoute
  '/skjema/$id': typeof SkjemaIdRouteWithChildren
  '/oversikt/': typeof OversiktIndexRoute
  '/representasjon/': typeof RepresentasjonIndexRoute
  '/skjema/': typeof SkjemaIndexRoute
  '/skjema/$id/arbeidsgiverens-virksomhet-i-norge': typeof SkjemaIdArbeidsgiverensVirksomhetINorgeRoute
  '/skjema/$id/arbeidssituasjon': typeof SkjemaIdArbeidssituasjonRoute
  '/skjema/$id/arbeidssted-i-utlandet': typeof SkjemaIdArbeidsstedIUtlandetRoute
  '/skjema/$id/arbeidstakerens-lonn': typeof SkjemaIdArbeidstakerensLonnRoute
  '/skjema/$id/familiemedlemmer': typeof SkjemaIdFamiliemedlemmerRoute
  '/skjema/$id/innsendt': typeof SkjemaIdInnsendtRoute
  '/skjema/$id/kvittering': typeof SkjemaIdKvitteringRoute
  '/skjema/$id/oppsummering': typeof SkjemaIdOppsummeringRoute
  '/skjema/$id/skatteforhold-og-inntekt': typeof SkjemaIdSkatteforholdOgInntektRoute
  '/skjema/$id/tilleggsopplysninger': typeof SkjemaIdTilleggsopplysningerRoute
  '/skjema/$id/utenlandsoppdraget': typeof SkjemaIdUtenlandsoppdragetRoute
  '/skjema/$id/utsendingsperiode-og-land': typeof SkjemaIdUtsendingsperiodeOgLandRoute
  '/skjema/$id/vedlegg': typeof SkjemaIdVedleggRoute
  '/skjema/$id/': typeof SkjemaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oversikt'
    | '/representasjon'
    | '/skjema'
    | '/representasjon/velg-radgiverfirma'
    | '/skjema/$id'
    | '/oversikt/'
    | '/representasjon/'
    | '/skjema/'
    | '/skjema/$id/arbeidsgiverens-virksomhet-i-norge'
    | '/skjema/$id/arbeidssituasjon'
    | '/skjema/$id/arbeidssted-i-utlandet'
    | '/skjema/$id/arbeidstakerens-lonn'
    | '/skjema/$id/familiemedlemmer'
    | '/skjema/$id/innsendt'
    | '/skjema/$id/kvittering'
    | '/skjema/$id/oppsummering'
    | '/skjema/$id/skatteforhold-og-inntekt'
    | '/skjema/$id/tilleggsopplysninger'
    | '/skjema/$id/utenlandsoppdraget'
    | '/skjema/$id/utsendingsperiode-og-land'
    | '/skjema/$id/vedlegg'
    | '/skjema/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/representasjon/velg-radgiverfirma'
    | '/oversikt'
    | '/representasjon'
    | '/skjema'
    | '/skjema/$id/arbeidsgiverens-virksomhet-i-norge'
    | '/skjema/$id/arbeidssituasjon'
    | '/skjema/$id/arbeidssted-i-utlandet'
    | '/skjema/$id/arbeidstakerens-lonn'
    | '/skjema/$id/familiemedlemmer'
    | '/skjema/$id/innsendt'
    | '/skjema/$id/kvittering'
    | '/skjema/$id/oppsummering'
    | '/skjema/$id/skatteforhold-og-inntekt'
    | '/skjema/$id/tilleggsopplysninger'
    | '/skjema/$id/utenlandsoppdraget'
    | '/skjema/$id/utsendingsperiode-og-land'
    | '/skjema/$id/vedlegg'
    | '/skjema/$id'
  id:
    | '__root__'
    | '/'
    | '/oversikt'
    | '/representasjon'
    | '/skjema'
    | '/representasjon/velg-radgiverfirma'
    | '/skjema/$id'
    | '/oversikt/'
    | '/representasjon/'
    | '/skjema/'
    | '/skjema/$id/arbeidsgiverens-virksomhet-i-norge'
    | '/skjema/$id/arbeidssituasjon'
    | '/skjema/$id/arbeidssted-i-utlandet'
    | '/skjema/$id/arbeidstakerens-lonn'
    | '/skjema/$id/familiemedlemmer'
    | '/skjema/$id/innsendt'
    | '/skjema/$id/kvittering'
    | '/skjema/$id/oppsummering'
    | '/skjema/$id/skatteforhold-og-inntekt'
    | '/skjema/$id/tilleggsopplysninger'
    | '/skjema/$id/utenlandsoppdraget'
    | '/skjema/$id/utsendingsperiode-og-land'
    | '/skjema/$id/vedlegg'
    | '/skjema/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OversiktRoute: typeof OversiktRouteWithChildren
  RepresentasjonRoute: typeof RepresentasjonRouteWithChildren
  SkjemaRoute: typeof SkjemaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skjema': {
      id: '/skjema'
      path: '/skjema'
      fullPath: '/skjema'
      preLoaderRoute: typeof SkjemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representasjon': {
      id: '/representasjon'
      path: '/representasjon'
      fullPath: '/representasjon'
      preLoaderRoute: typeof RepresentasjonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversikt': {
      id: '/oversikt'
      path: '/oversikt'
      fullPath: '/oversikt'
      preLoaderRoute: typeof OversiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skjema/': {
      id: '/skjema/'
      path: '/'
      fullPath: '/skjema/'
      preLoaderRoute: typeof SkjemaIndexRouteImport
      parentRoute: typeof SkjemaRoute
    }
    '/representasjon/': {
      id: '/representasjon/'
      path: '/'
      fullPath: '/representasjon/'
      preLoaderRoute: typeof RepresentasjonIndexRouteImport
      parentRoute: typeof RepresentasjonRoute
    }
    '/oversikt/': {
      id: '/oversikt/'
      path: '/'
      fullPath: '/oversikt/'
      preLoaderRoute: typeof OversiktIndexRouteImport
      parentRoute: typeof OversiktRoute
    }
    '/skjema/$id': {
      id: '/skjema/$id'
      path: '/$id'
      fullPath: '/skjema/$id'
      preLoaderRoute: typeof SkjemaIdRouteImport
      parentRoute: typeof SkjemaRoute
    }
    '/representasjon/velg-radgiverfirma': {
      id: '/representasjon/velg-radgiverfirma'
      path: '/velg-radgiverfirma'
      fullPath: '/representasjon/velg-radgiverfirma'
      preLoaderRoute: typeof RepresentasjonVelgRadgiverfirmaRouteImport
      parentRoute: typeof RepresentasjonRoute
    }
    '/skjema/$id/': {
      id: '/skjema/$id/'
      path: '/'
      fullPath: '/skjema/$id/'
      preLoaderRoute: typeof SkjemaIdIndexRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/vedlegg': {
      id: '/skjema/$id/vedlegg'
      path: '/vedlegg'
      fullPath: '/skjema/$id/vedlegg'
      preLoaderRoute: typeof SkjemaIdVedleggRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/utsendingsperiode-og-land': {
      id: '/skjema/$id/utsendingsperiode-og-land'
      path: '/utsendingsperiode-og-land'
      fullPath: '/skjema/$id/utsendingsperiode-og-land'
      preLoaderRoute: typeof SkjemaIdUtsendingsperiodeOgLandRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/utenlandsoppdraget': {
      id: '/skjema/$id/utenlandsoppdraget'
      path: '/utenlandsoppdraget'
      fullPath: '/skjema/$id/utenlandsoppdraget'
      preLoaderRoute: typeof SkjemaIdUtenlandsoppdragetRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/tilleggsopplysninger': {
      id: '/skjema/$id/tilleggsopplysninger'
      path: '/tilleggsopplysninger'
      fullPath: '/skjema/$id/tilleggsopplysninger'
      preLoaderRoute: typeof SkjemaIdTilleggsopplysningerRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/skatteforhold-og-inntekt': {
      id: '/skjema/$id/skatteforhold-og-inntekt'
      path: '/skatteforhold-og-inntekt'
      fullPath: '/skjema/$id/skatteforhold-og-inntekt'
      preLoaderRoute: typeof SkjemaIdSkatteforholdOgInntektRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/oppsummering': {
      id: '/skjema/$id/oppsummering'
      path: '/oppsummering'
      fullPath: '/skjema/$id/oppsummering'
      preLoaderRoute: typeof SkjemaIdOppsummeringRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/kvittering': {
      id: '/skjema/$id/kvittering'
      path: '/kvittering'
      fullPath: '/skjema/$id/kvittering'
      preLoaderRoute: typeof SkjemaIdKvitteringRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/innsendt': {
      id: '/skjema/$id/innsendt'
      path: '/innsendt'
      fullPath: '/skjema/$id/innsendt'
      preLoaderRoute: typeof SkjemaIdInnsendtRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/familiemedlemmer': {
      id: '/skjema/$id/familiemedlemmer'
      path: '/familiemedlemmer'
      fullPath: '/skjema/$id/familiemedlemmer'
      preLoaderRoute: typeof SkjemaIdFamiliemedlemmerRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/arbeidstakerens-lonn': {
      id: '/skjema/$id/arbeidstakerens-lonn'
      path: '/arbeidstakerens-lonn'
      fullPath: '/skjema/$id/arbeidstakerens-lonn'
      preLoaderRoute: typeof SkjemaIdArbeidstakerensLonnRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/arbeidssted-i-utlandet': {
      id: '/skjema/$id/arbeidssted-i-utlandet'
      path: '/arbeidssted-i-utlandet'
      fullPath: '/skjema/$id/arbeidssted-i-utlandet'
      preLoaderRoute: typeof SkjemaIdArbeidsstedIUtlandetRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/arbeidssituasjon': {
      id: '/skjema/$id/arbeidssituasjon'
      path: '/arbeidssituasjon'
      fullPath: '/skjema/$id/arbeidssituasjon'
      preLoaderRoute: typeof SkjemaIdArbeidssituasjonRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
    '/skjema/$id/arbeidsgiverens-virksomhet-i-norge': {
      id: '/skjema/$id/arbeidsgiverens-virksomhet-i-norge'
      path: '/arbeidsgiverens-virksomhet-i-norge'
      fullPath: '/skjema/$id/arbeidsgiverens-virksomhet-i-norge'
      preLoaderRoute: typeof SkjemaIdArbeidsgiverensVirksomhetINorgeRouteImport
      parentRoute: typeof SkjemaIdRoute
    }
  }
}

interface OversiktRouteChildren {
  OversiktIndexRoute: typeof OversiktIndexRoute
}

const OversiktRouteChildren: OversiktRouteChildren = {
  OversiktIndexRoute: OversiktIndexRoute,
}

const OversiktRouteWithChildren = OversiktRoute._addFileChildren(
  OversiktRouteChildren,
)

interface RepresentasjonRouteChildren {
  RepresentasjonVelgRadgiverfirmaRoute: typeof RepresentasjonVelgRadgiverfirmaRoute
  RepresentasjonIndexRoute: typeof RepresentasjonIndexRoute
}

const RepresentasjonRouteChildren: RepresentasjonRouteChildren = {
  RepresentasjonVelgRadgiverfirmaRoute: RepresentasjonVelgRadgiverfirmaRoute,
  RepresentasjonIndexRoute: RepresentasjonIndexRoute,
}

const RepresentasjonRouteWithChildren = RepresentasjonRoute._addFileChildren(
  RepresentasjonRouteChildren,
)

interface SkjemaIdRouteChildren {
  SkjemaIdArbeidsgiverensVirksomhetINorgeRoute: typeof SkjemaIdArbeidsgiverensVirksomhetINorgeRoute
  SkjemaIdArbeidssituasjonRoute: typeof SkjemaIdArbeidssituasjonRoute
  SkjemaIdArbeidsstedIUtlandetRoute: typeof SkjemaIdArbeidsstedIUtlandetRoute
  SkjemaIdArbeidstakerensLonnRoute: typeof SkjemaIdArbeidstakerensLonnRoute
  SkjemaIdFamiliemedlemmerRoute: typeof SkjemaIdFamiliemedlemmerRoute
  SkjemaIdInnsendtRoute: typeof SkjemaIdInnsendtRoute
  SkjemaIdKvitteringRoute: typeof SkjemaIdKvitteringRoute
  SkjemaIdOppsummeringRoute: typeof SkjemaIdOppsummeringRoute
  SkjemaIdSkatteforholdOgInntektRoute: typeof SkjemaIdSkatteforholdOgInntektRoute
  SkjemaIdTilleggsopplysningerRoute: typeof SkjemaIdTilleggsopplysningerRoute
  SkjemaIdUtenlandsoppdragetRoute: typeof SkjemaIdUtenlandsoppdragetRoute
  SkjemaIdUtsendingsperiodeOgLandRoute: typeof SkjemaIdUtsendingsperiodeOgLandRoute
  SkjemaIdVedleggRoute: typeof SkjemaIdVedleggRoute
  SkjemaIdIndexRoute: typeof SkjemaIdIndexRoute
}

const SkjemaIdRouteChildren: SkjemaIdRouteChildren = {
  SkjemaIdArbeidsgiverensVirksomhetINorgeRoute:
    SkjemaIdArbeidsgiverensVirksomhetINorgeRoute,
  SkjemaIdArbeidssituasjonRoute: SkjemaIdArbeidssituasjonRoute,
  SkjemaIdArbeidsstedIUtlandetRoute: SkjemaIdArbeidsstedIUtlandetRoute,
  SkjemaIdArbeidstakerensLonnRoute: SkjemaIdArbeidstakerensLonnRoute,
  SkjemaIdFamiliemedlemmerRoute: SkjemaIdFamiliemedlemmerRoute,
  SkjemaIdInnsendtRoute: SkjemaIdInnsendtRoute,
  SkjemaIdKvitteringRoute: SkjemaIdKvitteringRoute,
  SkjemaIdOppsummeringRoute: SkjemaIdOppsummeringRoute,
  SkjemaIdSkatteforholdOgInntektRoute: SkjemaIdSkatteforholdOgInntektRoute,
  SkjemaIdTilleggsopplysningerRoute: SkjemaIdTilleggsopplysningerRoute,
  SkjemaIdUtenlandsoppdragetRoute: SkjemaIdUtenlandsoppdragetRoute,
  SkjemaIdUtsendingsperiodeOgLandRoute: SkjemaIdUtsendingsperiodeOgLandRoute,
  SkjemaIdVedleggRoute: SkjemaIdVedleggRoute,
  SkjemaIdIndexRoute: SkjemaIdIndexRoute,
}

const SkjemaIdRouteWithChildren = SkjemaIdRoute._addFileChildren(
  SkjemaIdRouteChildren,
)

interface SkjemaRouteChildren {
  SkjemaIdRoute: typeof SkjemaIdRouteWithChildren
  SkjemaIndexRoute: typeof SkjemaIndexRoute
}

const SkjemaRouteChildren: SkjemaRouteChildren = {
  SkjemaIdRoute: SkjemaIdRouteWithChildren,
  SkjemaIndexRoute: SkjemaIndexRoute,
}

const SkjemaRouteWithChildren =
  SkjemaRoute._addFileChildren(SkjemaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OversiktRoute: OversiktRouteWithChildren,
  RepresentasjonRoute: RepresentasjonRouteWithChildren,
  SkjemaRoute: SkjemaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
